### PR TITLE
Email Subscription Form Update

### PR DESCRIPTION
**Pull request by lunchboxav**
As we're leaving Mailchimp and move to Hubspot, we need to remove the old email form that pushes the email subscription to Mailchimp and create a new form that sends the data to Hubspot. This also briefly explained in https://github.com/tetrateio/marcoms/issues/60.

This PR implements that new form that resides in the bottom of the footer, do some validation and sends the data to Hubspot.

Signed-off-by: Adityo Pratomo <adityo@tetrate.io>

### CODE REVIEW

**Comment by aditi-Kh** [comment]
@lunchboxav I tested this link: https://deploy-preview-128--getenvoy.netlify.app/. The form currently is placed at the end of the page.
Can we place it either:

- below the main banner, or
- below the install instructions?

**Comment by lunchboxav** [comment]
I think below the install instruction would be nicer. PTAL at the updated preview @aditi-Kh

**Comment by aditi-Kh** [comment]
This is perfect. Thanks, @lunchboxav! The records are also flowing into HubSpot as well.

**Comment by lunchboxav** [comment]
ugh, some Netlify issue. looking for a fix now.

**Comment by lunchboxav** [comment]
thank you very much @dio 🙌

**Pull request merged**
